parkinson/accounts/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup', views.signup, name='signup'), 
    url(r'^login', views.loginview, name='login'), 
]

parkinson/gesture/urls.py
# from django.urls import path
from gesture import views
from django.conf.urls import include, url
app_name="gesture"
urlpatterns = [
    url(r'handwriting', views.handwriting, name='handwriting'), 
    url(r'sleep', views.sleep, name='sleep'), 
    url(r'well', views.sleepwell, name='well'), 
    url(r'movement', views.movement, name='movement'),
    url(r'alert', views.sms, name='sms'),
    url(r'safe', views.safe, name='safe'),
    url(r'emergency', views.emergency, name='emergency'),
    url(r'success', views.send, name='send'),  
]

parkinson/parkinson/urls.py
from django.contrib import admin
# from django.urls import path
import gesture.views
import accounts.views
from django.conf.urls import include, url
#to get images
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', gesture.views.landing),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^gesture/', include('gesture.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

parkinson/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

parkinson/gesture/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

parkinson/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

def signup(request):
	if request.method == 'POST':
		if request.POST['password1'] == request.POST['password2']:
			try:
				# checking is username already exists
				user = User.objects.get(username=request.POST['username'])
				return render(request, 'accounts/signup.html', {'error': 'This username has already been taken'})
			except User.DoesNotExist:
				# logging in as the user
				user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
				login(request, user)
				return render(request, 'accounts/login.html')

		else:
			return render(request, 'accounts/signup.html', {'error': 'Passwords did not match'})

	else:
		return render(request, 'accounts/signup.html')

# how to log a user in : documentation
def loginview(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return render(request, 'gesture/index.html', {'error': 'Logged in successfully'})
		else:
			return render(request, 'accounts/login.html', {'error': 'Invalid username/password. Try again.'})
	else:
		return render(request, 'accounts/login.html')

parkinson/gesture/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from twilio.rest import Client

account_sid = 'AC1be5c12bbc465a99586baa2b766fc195'
auth_token = '756d2723cc1ff6dd08351f12f411326f'
client = Client(account_sid, auth_token)

def landing(request):
    return render(request, 'gesture/landing.html')

def movement(request):
    return render(request, 'gesture/gesture-detect.html')

def handwriting(request):
	return render(request, 'gesture/handwriting.html')

def sleep(request):
	return render(request, 'gesture/sleep.html')

def sleepwell(request):
	return render(request, 'gesture/sleepwell.html')

def sms(req):
    return render(req, 'gesture/base.html')

def safe(req):
    message = client.messages \
        .create(
        body="Patient is Safe.",
        from_='+18327261605',
        to='+918851465800'
    )
    print(message.sid)
    return render(req,'gesture/safe.html')

def emergency(req):
    message = client.messages \
        .create(
        body="Please check on patient. EMERGENCY",
        from_='+18327261605',
        to='+918851465800'
    )
    print(message.sid)
    return render(req, 'gesture/unsafe.html')

def send(req):
    message = client.messages \
        .create(
        body="Your Loved One is on the Move.",
        from_='+18327261605',
        to='+918851465800'
    )
    print(message.sid)
    return render(req, 'gesture/success.html')

parkinson/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8">

  <title>Login Form</title>

    <style>
@import url(http://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background-image: url(https://images.unsplash.com/photo-1553548146-50f0bdf09f0e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=701&q=80);
	background-size: cover;
	-webkit-filter: blur(5px);
	z-index: 0;
}

.grad{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: absolute;
	top: calc(50% - 35px);
	left: calc(50% - 255px);
	z-index: 2;
}

.header div{
	float: left;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: black
}

.login{
	position: absolute;
	top: calc(50% - 75px);
	left: calc(50% - 50px);
	height: 150px;
	width: 350px;
	padding: 10px;
	z-index: 2;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

.login input[type=password]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}

.login input[type=button]{
	width: 260px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

.login input[type=button]:hover{
	opacity: 0.8;
}

.login input[type=button]:active{
	opacity: 0.6;
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=password]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=button]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
}
</style>
</head>

<body>

  <div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Parkinson<span>Pal</span></div>
		</div>
		<br>
		<div class="login">
				<input type="text" placeholder="username" name="user"><br>
				<input type="password" placeholder="password" name="password"><br>
				<input type="button" value="Login">
		</div>

  <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>

</body>

</html>

parkinson/accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>

<head>

  <meta charset="UTF-8">

  <title>Sign Up Form</title>

    <style>
@import url(http://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background-image: url(http://ginva.com/wp-content/uploads/2012/07/city-skyline-wallpapers-008.jpg);
	background-size: cover;
	-webkit-filter: blur(5px);
	z-index: 0;
}

.grad{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: absolute;
	top: calc(50% - 35px);
	left: calc(50% - 255px);
	z-index: 2;
}

.header div{
	float: left;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: black;
}

.login{
	position: absolute;
	top: calc(50% - 75px);
	left: calc(50% - 50px);
	height: 150px;
	width: 350px;
	padding: 10px;
	z-index: 2;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

.login input[type=password]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}

.login input[type=button]{
	width: 260px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

.login input[type=button]:hover{
	opacity: 0.8;
}

.login input[type=button]:active{
	opacity: 0.6;
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=password]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=button]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
}
</style>
</head>

<body>

  <div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Parkinson<span>Pal</span></div>
		</div>
		<br>
		<div class="login">
				<input type="text" placeholder="username" name="user"><br>
				<input type="password" placeholder="password" name="password"><br>
				<input type="password" placeholder="confirm password" name="password"><br>
				<input type="button" value="Sign Up">
		</div>

  <script src='http://codepen.io/assets/libs/fullpage/jquery.js'></script>

</body>

</html>

parkinson/gesture/templates/gesture/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/base.css' %}">
    <meta charset="UTF-8">
    <title>SOS</title>
</head>
<body>
	<div class="container">
		<h2 style="text-align: center;">Send an alert when you're on the move!</h2>
		<form action="{% url 'gesture:send' %}" method="get">
			    <input type="submit" value="Send Alert" id="move">
		</form>
			
			<h2 style="text-align: center;">Mission Accomplished! Mark yourself safe!</h2>
			<form action="{% url 'gesture:safe' %}" name="frm1">
			    <input type="submit" value="Mark Safe" id="safe">
		</form>
	</div>

<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
</body>
</html>

parkinson/gesture/templates/gesture/gesture-detect.html
<html>

<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>Exercising</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.dom.min.js"></script>
  <script src="https://unpkg.com/ml5@0.2.2/dist/ml5.min.js" type="text/javascript"></script>
  <link rel="stylesheet" type="text/css" href="{% static '../static/css/detect.css' %}">
</head>

<body>
  <h1 align="center">Exercise Time</h1>
  <img id='immu' src="{% static 'pictures/yoga4.jpg' %}" height="500px" width="400px">
  <p id='faltu' style="font-size: 50px; border-style: solid;border-width: 7px;border-color: black;display: inline; margin-left: 70px" ></p>
</body>

<script type="text/javascript">
let video;
let poseNet;
let poses = [];
var ind2=0;
function setup() {
  var cnv=createCanvas(400, 500);
  var x = (windowWidth - width) /1.01;
  var y = (windowHeight - height) / 2.5;
  cnv.position(x, y);
  video = createCapture(VIDEO);
  video.size(width, height);
  ind2=1;
  // Create a new poseNet method with a single detection
  poseNet = ml5.poseNet(video, modelReady);
  // This sets up an event that fills the global variable "poses"
  // with an array every time new poses are detected
  poseNet.on('pose', function(results) {
    poses = results;
  });
  // Hide the video element, and just show the canvas
  video.hide();
}

var myVar = setInterval(answer_gen, 7000);
var ind = 0;
var ind3 = 0;

function pictureChange(){
  items = ['pictures/yoga1.jpg', 'pictures/yoga2.jpg', 'pictures/yoga3.jpg', 'pictures/yoga4.jpg']

  if(document.getElementById("faltu").innerHTML=='Yayy, you did it Right' && ind<items.length){
    var item = items[ind];
    if(ind==1&&item!=undefined){
      document.getElementById("faltu").innerHTML = "";
        document.getElementById("immu").src="{% static 'pictures/yoga1.jpg' %}";
        ind++;
    }
    else if(ind==2&&item!=undefined){
      document.getElementById("faltu").innerHTML = "";
        document.getElementById("immu").src="{% static 'pictures/yoga3.jpg' %}";
        ind++;
    }
    else if(ind==3&&item!=undefined){
      document.getElementById("faltu").innerHTML = "";
        document.getElementById("immu").src="{% static 'pictures/yoga4.jpg' %}";
        ind++;
    }
    else{
      document.getElementById("faltu").innerHTML = "";
        document.getElementById("immu").src="{% static 'pictures/yoga2.jpg' %}";
        ind++;
    }
  }

  if(ind==4){
    document.getElementById("faltu").innerHTML = "BYE BYE!";
        document.getElementById("immu").src="{% static 'pictures/sunset.jpg' %}";
  }
}

function answer_gen(){
  var items = ["Welcome to the Test","Yayy, you did it Right", "You Can Do Better","This didn't go fine","You Can Do Better","Yayy, you did it Right"]
  
  if(ind2!=0 && ind2!=undefined){
    var item = items[ind3];
    document.getElementById("faltu").innerHTML = item;
    var myvar2 = setInterval(pictureChange, 10000)
    if(ind3==items.length-1){
      ind3 = 1;
    }else{
      ind3= (ind3+1)%items.length;
    }
  }
}

function modelReady() {
  //select('#status').html('Model Loaded');
}

function draw() {
  image(video, 0, 0, width, height);

  // We can call both functions to draw all keypoints and the skeletons
  drawKeypoints();
  drawSkeleton();
}

// A function to draw ellipses over the detected keypoints
function drawKeypoints()  {
  // Loop through all the poses detected
  for (let i = 0; i < poses.length; i++) {
    // For each pose detected, loop through all the keypoints
    let pose = poses[i].pose;
    for (let j = 0; j < pose.keypoints.length; j++) {
      // A keypoint is an object describing a body part (like rightArm or leftShoulder)
      let keypoint = pose.keypoints[j];
      // Only draw an ellipse is the pose probability is bigger than 0.2
      if (keypoint.score > 0.2) {
        fill(255, 0, 0);
        noStroke();
        ellipse(keypoint.position.x, keypoint.position.y, 10, 10);
      }
    }
  }
}

// A function to draw the skeletons
function drawSkeleton() {
  // Loop through all the skeletons detected
  for (let i = 0; i < poses.length; i++) {
    let skeleton = poses[i].skeleton;
    // For every skeleton, loop through all body connections
    for (let j = 0; j < skeleton.length; j++) {
      let partA = skeleton[j][0];
      let partB = skeleton[j][1];
      stroke(255, 0, 0);
      line(partA.position.x, partA.position.y, partB.position.x, partB.position.y);
    }
  }
}
</script>
<!-- <script src = "{% static 'js/sketch.js' %}">
  DJANGO_STATIC_URL = '{{ STATIC_URL }}';
</script> -->
</html>

parkinson/gesture/templates/gesture/handwriting.html
<!DOCTYPE HTML>


{% load static %}
<html manifest="letterpaint.manifest" lang="en-US">
<head>
  <meta name="viewport" content="width=device-width">
  <meta charset="UTF-8">
  <title>Steady Writing</title>

  <link rel="stylesheet" type="text/css" href="{% static '../static/css/letterpaint.css' %}">
</head>


<body>
  <div id="container" class="container">

    <div id="chars" class="gamedata">ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz123456789</div>

    <canvas></canvas>

    <h1 class="toppanel">Test your Handwriting here</h1>

    <div id="intro" class="cover">
      <p>Improve the steadiness of your hand and try to paint over the letter you see on the screen without going outside of it!</p>
      <button class="actionbutton">➜</button>
    </div>

    <button id="sound" class="navbutton">♬</button>
    <button id="infos" class="navbutton">i</button>

    <div id="win" class="cover check">
      <p>Good job!</p>
      <button class="actionbutton">➜</button>
    </div>

    <div id="error" class="cover">
      <p>You painted outside the letter!</p>
      <button class="actionbutton">➜</button>
    </div>

    <div id="info" class="cover infopanel">
      <!-- <h1>letterpaint</h1> -->
      <!-- <p>version 1.0</p> -->
      <!-- <p>Written by Chris Heilmann</p> -->
      <button id="install" class="inlinebutton">Install this</button>
    </div>

    <button class="actionbutton undo" id="reload">X</button>
  </div>

  <!-- http://freesound.org/people/NenadSimic/sounds/150879/ -->
  <audio src="{% static '../static/audio/win.ogg' %}" id="winsound"></audio>
  <!-- http://freesound.org/people/Autistic%20Lucario/sounds/142608/ -->
  <audio src="{% static '../static/audio/error.ogg' %}" id="errorsound"></audio>

  <script src="{% static '../static/js/letterpaint.js' %}"></script>
</body>
</html>

parkinson/gesture/templates/gesture/landing.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Landing</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/landing.css' %}">
	<style type="text/css">body{
		background-image: url(https://images.unsplash.com/photo-1488554378835-f7acf46e6c98?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80);
		background-repeat: no-repeat;
		background-size: cover;
		 background-position: center;
	}</style>
</head>
<body>
	<!-- <nav class="navbar navbar-expand-sm bg-danger navbar-danger sticky-top ">
		<ul class="navbar-nav justify-content-left">
    <li class="nav-item">
      <a class="nav-link" href="#" style="color: white">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#" style="color: white">Sign Up</a>
    </li>
		</nav> -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Parkinson Pal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    
    <!-- <span class="navbar-text">
      Navbar text with an inline element
    </span> -->

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/accounts/login">Login <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/accounts/signup">SignUp <span class="sr-only">(current)</span></a>
      </li>
      
    </ul>
  </div>
</nav>
		<br>

    <div>
        <table>
            <tr>
                <td>
                    <a href="/gesture/handwriting"><img class="image" src="{% static '../static/pictures/letter-put.jpeg' %}"></a>
                    <h3 class="heading">Steady Writing</h3>
                </td>
                <td>
                    <a href="/gesture/well"><img class="image" src="{% static '../static/pictures/sleep-put.jpg' %}"></a>
                    <h3 class="heading">Bed Time</h3>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="/gesture/alert"><img class="image" src="{% static '../static/pictures/sos-put.jpg' %}"></a>
                    <h3 class="heading">On the Move</h3>
                </td>
                <td>
                    <a href="/gesture/movement"><img class="image" src="{% static '../static/pictures/Fitness-put.jpg' %}"></a>
                    <h3 class="heading">Exercise Right</h3>
                </td>
            </tr>
        </table>

        <iframe
            allow="microphone;"
            width="350"
            height="500"
            src="https://console.dialogflow.com/api-client/demo/embedded/f010f72f-b850-4ab2-9497-83de15b538ea" style="width: 300px;
            border: 1px solid #ccc;
            display: inline;
            float: right;
            margin-right: 20px;
            margin-top: -520px;
            margin-left: 800px;
        ">
        </iframe>
    </div>

	<!-- <div class="container" style="margin-left: 130px; display: inline;" > -->
    
</div>

</body>
</html>

parkinson/gesture/templates/gesture/safe.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/base.css' %}">
    <meta charset="UTF-8">
    <title>Safe</title>
</head>
<body>
	<div class="container">
		<h1>Patient is Safe!</h1>
	</div>
</body>
</html>

parkinson/gesture/templates/gesture/sleep.html
<!DOCTYPE html>
<html>
<head>
	<title>DataSet</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<style type="text/css">
		body{
			background: url("https://images.unsplash.com/photo-1522764725576-4cbbbf12c16d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=564&q=80");
		}

		form {
  padding: 70px 0;
  border: 3px;
  text-align: center;
}

p{
	color: white;
	font-size: 15px;
}

h3{
	color: white;
	
}

input[type=text] {
  
  
  box-sizing: border-box;
  border: none;
  border-bottom: 2px solid #9e1948;
}
	</style>
</head>
<body>
	<div class="container" class="center" >

	<form>
        <div style="background-color: #69102f "><h3>Enter The Number Of Hours It Took You To Sleep Each Day, This Week :</h3></div>
		<br>
		<p>Monday :<p>  </p><input type="text" name="Monday"></p>		
		<br>
		<p>Tuesday: <p>  </p>  <input type="text" name="Tuesday"></p>
		<br>
		<p>Wednesday:<p>  </p> <input type="text" name="Wednesday"></p>
		<br>
		<p>Thursday:<p>  </p>  <input type="text" name="Thursday"></p>
		<br>
		<p>Friday:  <p>  </p>  <input type="text" name="Friday"></p>
		
	</form>
	</div>
</body>
</html>

parkinson/gesture/templates/gesture/sleepwell.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<title>Bed Time</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial;
  font-size: 17px;
}

#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
}

.content {
  position: fixed;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  color: #f1f1f1;
  width: 100%;
  padding: 20px;
}

button {
  width: 200px;
  font-size: 18px;
  padding: 10px;
  border: none;
  background: #000;
  color: #fff;
  cursor: pointer;
}

button:hover {
  background: #ddd;
  color: black;
}
</style>
</head>
<body>

<video autoplay muted loop id="myVideo">
  <source src="https://media.giphy.com/media/3o7qDNfxtNRtLVv8qs/giphy.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>



<div class="content">
     <h1>Sleep Well!</h1>
  <div>
    <audio id="myAudio">
  <source src="{% static '../static/audio/stairway.mp3' %}" type="audio/mp3">
</audio>

<p>It was a tiring day, so lay back and relax, we hope you sleep early today.</p>

<button onclick="playAudio()" type="button">Play Audio!</button>
<button id="myBtn" onclick="myFunction()" type="button">Start Timer!</button>
<form action="{% url 'gesture:sleep' %}">
  <button type="submit">Input</button>
</form>
  </div>
  
</div>

<script>

var x = document.getElementById("myAudio"); 

var hours = [1,2,1,1,2];

var sum=0;

hours.forEach(function(item, index, array) {
  sum+=item;
});

var y=((sum/5)*(60*60*1000))/100;



function myFunction() {
  setTimeout(function pauseAudio() { 
  x.pause(); 
  
} , 5000);
}

function playAudio() { 
  x.play(); 
} 


</script>

</body>
</html>

parkinson/gesture/templates/gesture/success.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/base.css' %}">
    <title>Success</title>
</head>
<body onload="setTimeout(function() { document.frm1.submit() }, 7000)">
	<div class="container">
		<h1>Member Alerted Successfully!</h1>

		<form action="{% url 'gesture:emergency' %}" name="frm1">

		</form>

		<form action="{% url 'gesture:safe' %}">
		    <input type="submit" value="Safe" id="safe">
		</form>
	</div>
</body>
</html>

parkinson/gesture/templates/gesture/unsafe.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '../static/css/base.css' %}">
    <title>Unsafe</title>
</head>
<body>
	<div class="container">
		<h1>Something is Wrong. Please Check.</h1>
	</div>
</body>
</html>